# Generated by Django 5.2.1 on 2025-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagina_Principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(default=64000, max_length=10),
            preserve_default=False,
        ),
    ]
